Repository swagger-api/swagger-ui, pull requests merged in 2020-06, with the labels that each got.

#6130 fix(Markdown): render markdown in more secure way
  docker/configurator/variables.js
  docs/usage/configuration.md
  src/core/components/array-model.jsx
  src/core/components/auth/api-key-auth.jsx
  src/core/components/auth/basic-auth.jsx
  src/core/components/auth/oauth2.jsx
  src/core/components/example.jsx
  src/core/components/headers.jsx
  src/core/components/info.jsx
  src/core/components/object-model.jsx
  src/core/components/operation-tag.jsx
  src/core/components/operation.jsx
  src/core/components/parameter-row.jsx
  src/core/components/primitive-model.jsx
  src/core/components/providers/markdown.jsx
  src/core/components/response.jsx
  src/core/plugins/oas3/components/callbacks.jsx
  src/core/plugins/oas3/components/http-auth.jsx
  src/core/plugins/oas3/components/operation-link.jsx
  src/core/plugins/oas3/components/request-body.jsx
  src/core/plugins/oas3/wrap-components/markdown.jsx
  test/mocha/components/markdown.jsx
Labels: cat: configuration, cat: rendering, type: enhancement, version: 3.x

#6165 Added entrySeq() to Callbacks map() to fix React 16 + Immutable issue
  src/core/plugins/oas3/components/callbacks.jsx
Labels: version: 3.x

#5930 Fixed rendering of Common Extensions in React 16
  src/core/components/parameter-row.jsx
  src/core/plugins/oas3/components/request-body.jsx
Labels: type: bug, version: 3.x

#6182 build(webpack): make sure we're not bundling same deps twice
  webpack/bundle.babel.js
Labels: type: enhancement, version: 3.x
