Repository swagger-api/swagger-ui, pull requests merged in 2021-11, with the labels that each got.

#7574 docs(LICENSE): apply Apache 2.0 License correctly
  .npmignore
  LICENSE
  NOTICE
  flavors/swagger-ui-react/release/run.sh
  swagger-ui-dist-package/deploy.sh
Labels: type: enhancement

#7584 chore(deps): fix security vulnerabilities
  package-lock.json
Labels: cat: security, dependencies, security fix

#7604 docs(README): add v4.0.0 into compatiblity table
  README.md
Labels: cat: documentation

#7611 fix(servers): prevent UI crash when chaning Server with variables
  src/core/components/info.jsx
  src/core/components/operation-tag.jsx
  src/core/components/operation.jsx
  src/core/utils/url.js
  test/unit/core/utils.js
Labels: type: bug, version: 4.x

#7614 fix(highlight-code): fix regression code highlight behavior
  src/core/components/highlight-code.jsx
Labels: type: regression, version: 4.x

#7601 Add source map of css file to swagger-ui-react
  flavors/swagger-ui-react/release/run.sh
Labels: type: enhancement, version: 4.x

#7619 fix(swagger-ui-react): add showExtension propType
  flavors/swagger-ui-react/index.jsx
Labels: type: enhancement, version: 4.x

#7620 docs(configuration): document requestSnippetsEnabled config option
  docs/usage/configuration.md
Labels: cat: documentation, type: enhancement, version: 4.x

#7536 Ft/request snippets react
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
Labels: type: feature, version: 3.x, version: 4.x

#7669 chore(deps-dev): fix security vuln. in react-syntax-highlighter
  package-lock.json
  package.json
Labels: cat: security, security fix, version: 4.x

#7671 fix: error boundaries
  config/jest/jest.unit.config.js
  src/core/components/layouts/base.jsx
  src/core/plugins/view/error-boundary.jsx
  src/core/plugins/view/fallback.jsx
  src/core/plugins/view/index.js
  src/core/plugins/view/root-injects.jsx
  src/standalone/layout.jsx
  test/unit/core/system/system.jsx
Labels: type: regression

#7680 fix: request JumpToPath components always as container
  package-lock.json
  src/core/components/models.jsx
Labels: type: bug, version: 4.x
