Repository swagger-api/swagger-ui, pull requests merged in 2021-09, with the labels that each got.

#7489 fix(security): bump swagger-client to v3.16.1
  package-lock.json
  package.json
Labels: version: 3.x, dependencies, security vulnerability, security fix

#7491 fix(build-security): do not expose hostname to build framents
  src/core/index.js
  webpack/_config-builder.js
Labels: cat: security, security vulnerability, security fix, version: 4.x

#7493 fix(security): fix security issue in prismjs dep
  package-lock.json
  package.json
Labels: cat: security, version: 3.x, security vulnerability, security fix

#7496 fix(Dockerfile): fix security issue in docker image
  Dockerfile
Labels: cat: security, version: 3.x, cat: docker, security vulnerability, security fix

#7495 fix(try-it-out): Fix the width of image responses
  src/core/components/response-body.jsx
  src/style/_layout.scss
Labels: type: bug, version: 3.x

#7432 fix(sample-gen): Generate the correct number of additionalProperties when minProperties is used
  src/core/plugins/samples/fn.js
  test/unit/core/plugins/samples/fn.js
Labels: type: bug, version: 3.x

#7509 docs(configuration): fix wrong property name
  docs/usage/configuration.md
Labels: cat: documentation, version: 3.x, type: enhancement

#7510 chore(security): fix security vulnerabilities in dev deps
  package-lock.json
Labels: cat: security, version: 3.x, security vulnerability, security fix

#7464 [BUG-7463] Response example tabs a11y
  src/core/components/model-example.jsx
  test/e2e-cypress/tests/a11y/response-tabs.js
  test/e2e-cypress/tests/bugs/swos-63.js
Labels: type: enhancement, cat: a11y

#7517 fix(style): update the buttons of the example tabs to be displayed as links
  src/style/_layout.scss
Labels: type: regression, cat: a11y

#7520 chore(deps-dev): fix security vulnerabilities in dep tree
  package-lock.json
Labels: cat: security, dependencies, security vulnerability, security fix

#7526 Remove IE7 CSS hack
  src/style/_mixins.scss
Labels: version: 3.x, type: housekeeping, version: 4.x

#7516 fix: break path w/ <wbr>s to avoid copying ZWSPs
  src/core/components/deep-link.jsx
  src/core/components/operation-summary-path.jsx
Labels: version: 3.x, type: enhancement, cat: user experience, version: 4.x

#7527 fix: correct width of http request methods
  src/style/_layout.scss
Labels: version: 3.x, type: enhancement, cat: style & presentation, version: 4.x
