Repository swagger-api/swagger-ui, pull requests merged in 2022-08, with the labels that each got.

#8137 fix(build): mitigate regressions to build framents in v4.13.1
  babel.config.js
  package-lock.json
  package.json
Labels: type: regression

#8142 docs(setting-up): reword how SwaggerUI reflects Node.js releases
  docs/development/setting-up.md
  test/unit/jest-shim.js
Labels: cat: documentation, type: enhancement

#7559 Render links to external docs
  src/core/components/array-model.jsx
  src/core/components/object-model.jsx
  src/core/components/operation-tag.jsx
  src/core/components/operation.jsx
  src/core/components/primitive-model.jsx
  src/style/_layout.scss
  src/style/_models.scss
  test/e2e-cypress/static/documents/features/external-docs.openapi.yaml
  test/e2e-cypress/static/documents/features/external-docs.swagger.yaml
  test/e2e-cypress/tests/features/external-docs.js
Labels: type: enhancement
