Repository swagger-api/swagger-ui, pull requests merged in 2022-01, with the labels that each got.

#7745 chore(whitesource): update configuration file
  .whitesource
  whitesource.config
Labels: cat: security

#7746 chore(package-lock): run npm audit to fix security vunls
  package-lock.json
Labels: cat: security, dependencies, version: 4.x

#7717 Add source map of js files to swagger-ui-react
  flavors/swagger-ui-react/release/run.sh
Labels: type: enhancement, version: 4.x, javascript

#7705 feat: add support of defaultModelRendering prop to swagger-ui-react
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
Labels: cat: configuration

#7524 document request snippets plug points
  docs/customization/plug-points.md
Labels: cat: documentation, type: enhancement

#7759 chore(package-lock): fix security vulnerabilities
  package-lock.json
Labels: cat: security, dependencies, security fix

#7522 Enable displayRequestDuration prop for react
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
Labels: type: feature, type: enhancement, cat: configuration

#7670 chore(deps): bump serialize-error from 8.1.0 to 9.0.0
  config/jest/jest.artifact.config.js
  config/jest/jest.unit.config.js
  package-lock.json
  package.json
Labels: dependencies, version: 4.x

#7772 chore(deps): update swagger-client to v3.18.2
  package-lock.json
  package.json
Labels: type: regression, dependencies, version: 4.x

#7775 revert: add wait time for bugs/5043 to resolve spec (#7769)
  test/e2e-cypress/tests/bugs/5043.js
Labels: version: 4.x

#7777 revert: bump serialize-error from 8.1.0 to 9.0.0 (#7670)
  config/jest/jest.artifact.config.js
  config/jest/jest.unit.config.js
  package-lock.json
  package.json
Labels: type: regression, version: 4.x

#7761 feat(error-boundary): add support to override error handling
  config/jest/jest.unit.config.js
  docs/customization/plug-points.md
  src/core/components/highlight-code.jsx
  src/core/components/layouts/base.jsx
  src/core/plugins/all.js
  src/core/plugins/oas3/components/request-body.jsx
  src/core/plugins/safe-render/components/error-boundary.jsx
  src/core/plugins/safe-render/components/fallback.jsx
  src/core/plugins/safe-render/fn.jsx
  src/core/plugins/safe-render/index.js
  src/core/plugins/view/fn.js
  src/core/plugins/view/index.js
  src/core/plugins/view/root-injects.jsx
  src/core/presets/base.js
  src/standalone/index.js
  src/standalone/layout.jsx
  test/unit/core/plugins/auth/actions.js
  test/unit/core/plugins/safe-render/index.jsx
  test/unit/core/system/system.jsx
Labels: type: enhancement

#7795 fix(swagger-ui-react): fix prop type for defaultModelRendering
  flavors/swagger-ui-react/index.jsx
Labels: type: regression, version: 4.x

#7438 feat: do not ask for client secret when using auth code with PKCE
  src/core/components/auth/oauth2.jsx
  test/e2e-cypress/static/documents/features/auth-code-flow-pkce-without-secret.yaml
  test/e2e-cypress/tests/features/auth-code-flow-pkce-without-secret.js
Labels: cat: auth, type: enhancement

#7798 fix(security): update swagger-client to v3.18.3
  package-lock.json
  package.json
Labels: cat: security, security fix, version: 4.x

#7744 update JDK documentation link
  README.md
Labels: cat: documentation, type: enhancement

#7753 change swagger-js wrapActions to js object
  src/core/plugins/swagger-js/index.js
Labels: type: enhancement, version: 4.x

#7799 refactor(memoize): get rid of memoizee prod dependency
  package-lock.json
  package.json
  src/core/plugins/samples/fn.js
  src/helpers/memoizeN.js
Labels: type: enhancement, dependencies, version: 4.x

#7801 fix(view-plugin): provide resolvers for memoized functions
  src/core/plugins/view/index.js
Labels: type: enhancement, version: 4.x

#7805 refactor(memoizeN): extract support code out of closure
  src/helpers/memoizeN.js
Labels: type: enhancement, version: 4.x

#7815 fix(auth): compensate for uninitialized config
  src/core/components/auth/oauth2.jsx
Labels: type: regression, type: enhancement, version: 4.x
