Repository swagger-api/swagger-ui, pull requests merged in 2022-03, with the labels that each got.

#7869 chore(deps): fix security vulnerabilities
  package-lock.json
  package.json
Labels: cat: security, dependencies

#7842 Enable persistAuthorization prop for React
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
Labels: type: enhancement

#7900 fix(swagger-ui-react): amend prop validation for plugins
  flavors/swagger-ui-react/index.jsx
Labels: type: enhancement

#7743 add name tag to bearer input field
  src/core/plugins/oas3/components/http-auth.jsx
Labels: cat: a11y

#7474 feat: add OAUTH_USE_BASIC_AUTH to docker builds
  dev-helpers/index.html
  docker/configurator/oauth.js
  docs/usage/oauth2.md
  test/unit/docker/oauth.js
Labels: cat: docker

#7927 feat(swagger-ui-react): export presets and plugins as static props
  flavors/swagger-ui-react/index.jsx
Labels: type: feature

#7937 feat(build): expose true ESM bundle as primary artifact
  config/jest/jest.artifact.config.js
  package-lock.json
  package.json
  webpack/_config-builder.js
  webpack/es-bundle-core.babel.js
  webpack/es-bundle.babel.js
Labels: type: enhancement

#7946 feat(build): add support for Create React App without eject
  webpack/es-bundle-core.babel.js
Labels: type: enhancement

#7327 Add LICENSE
  README.md
Labels: cat: documentation
