Repository swagger-api/swagger-ui, pull requests merged in 2023-09, with the labels that each got.

#9191 fix(swagger-ui-react): fix build scripts and allow releasing
  babel.config.js
  flavors/swagger-ui-react/release/run.sh
Labels: type: bug, version: 5.x

#9194 fix(swagger-ui-react): avoid babel output in build fragments
  babel.config.js
Labels: type: bug, version: 5.x

#9196 refactor: utilize nested wrapping
  src/core/plugins/oas3/components/auth/http-auth.jsx
  src/core/plugins/oas3/components/index.js
  src/core/plugins/oas3/wrap-components/auth/auth-item.jsx
  src/core/plugins/oas3/wrap-components/index.js
  src/core/plugins/oas31/components/auth/auths.jsx
  src/core/plugins/oas31/components/auth/mutual-tls-auth.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/wrap-components/auth-item.jsx
  src/core/plugins/oas31/wrap-components/auth/auth-item.jsx
Labels: type: enhancement, version: 5.x

#9197 refactor: reuse selector logic
  src/core/plugins/oas3/index.js
  src/core/plugins/oas31/auth-extensions/wrap-selectors.js
Labels: type: enhancement, version: 5.x

#8999 Provide additional context for authorization and logout button
  src/core/components/auth/auths.jsx
  src/core/components/auth/oauth2.jsx
  test/e2e-cypress/e2e/features/oauth2-flows/application.cy.js
  test/e2e-cypress/e2e/security/apikey.cy.js
Labels: type: enhancement, version: 5.x

#9204 build: use Node.js =20.3.0 for local dev env
  .github/workflows/nodejs.yml
  .github/workflows/release-swagger-ui-react.yml
  .github/workflows/release-swagger-ui.yml
  .nvmrc
  babel.config.js
  docs/development/setting-up.md
Labels: type: enhancement, version: 5.x

#9205 refactor: use document.baseURI for URI Reference resolution
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9207 build(babel): use browserslist explicitly
  .browserslistrc
  babel.config.js
  flavors/swagger-ui-react/release/run.sh
  package-lock.json
  package.json
Labels: type: enhancement, version: 5.x

#9209 fix(security): allow more strict CSP for SVG assets
  dev-helpers/index.html
  package-lock.json
  package.json
  src/core/components/model.jsx
  src/core/components/operation.jsx
  src/standalone/plugins/top-bar/components/Logo.jsx
  webpack/_config-builder.js
  webpack/dev.js
Labels: cat: security, version: 5.x

#9214 fix(resolve): make retrievalURL absolute before resolution
  dev-helpers/index.html
  src/core/index.js
  src/core/plugins/spec/actions.js
Labels: type: regression, version: 5.x

#9223 fix(callbacks): display all defined callbacks
  src/core/plugins/oas3/spec-extensions/selectors.js
  test/e2e-cypress/e2e/features/oas3-callbacks.cy.js
  test/e2e-cypress/static/documents/features/oas3-callbacks.yaml
Labels: version: 5.x

#9230 feat(operation-summary): collapse after jumptopath
  src/core/components/operation-summary.jsx
Labels: type: enhancement, version: 5.x

#9264 feat: add wrapper for version labels
  src/core/components/info.jsx
  test/unit/xss/info-sanitization.jsx
Labels: type: enhancement, version: 5.x

#9267 feat: add wrapper for version labels for OAS 3.1 spec
  src/core/plugins/oas31/components/info.jsx
Labels: type: enhancement, version: 5.x

#9265 fix table issue at README.md
  README.md
Labels: cat: documentation, type: enhancement, version: 5.x
