Repository swagger-api/swagger-ui, pull requests merged in 2023-06, with the labels that each got.

#8874 ci(docker): distinguish docker_ref and git_ref inputs
  .github/workflows/docker-build-push.yml
Labels: docker

#8876 ci(docker): add support for `repository_dispatch` event type
  .github/workflows/docker-build-push.yml
Labels: type: enhancement, cat: docker, docker

#8883 feat(samples): add support for type keyword defined as list of types
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8884 feat(samples): add support for const keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: version: 5.x

#8885 feat(samples): support new semantics of exclusive number ranges
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8886 refactor(samples): add better support for exclusive number ranges
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: enhancement, version: 5.x

#8887 fix(oas31): fix rendering of Schema Object inside Operation Object
  src/core/plugins/oas31/wrap-components/model.jsx
Labels: type: bug, version: 5.x

#8890 feat(samples): support multipleOf keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8891 feat(samples): add support for regex string format
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8896 feat(samples): add support for contains, minContains, maxContains keywords
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: version: 5.x

#8897 refactor(samples): type check string constrains according to spec
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: enhancement, version: 5.x

#8898 refactor(samples): type check object constraints acording to spec
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: enhancement, version: 5.x

#8899 feat(samples): add support for contentEncoding keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8900 refactor(samples): extract number and string constrains applicators
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: enhancement, version: 5.x

#8903 feat(samples): add support for contentMediaType keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8905 feat(samples): add support for custom formats, encoders and media types
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/api/encoderAPI.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/api/formatAPI.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/api/mediaTypeAPI.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/class/EncoderRegistry.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/class/MediaTypeRegistry.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/class/Registry.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/random.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/utils.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/7bit.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/8bit.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/base16.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/base32.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/base64.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/binary.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/encoders/quoted-printable.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/date-time.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/date.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/double.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/duration.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/email.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/float.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/hostname.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/idn-email.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/idn-hostname.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/int32.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/int64.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/ipv4.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/ipv6.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/iri-reference.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/iri.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/json-pointer.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/media-types/application.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/media-types/audio.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/media-types/image.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/media-types/text.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/media-types/video.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/password.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/regex.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/relative-json-pointer.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/time.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/uri-reference.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/uri-template.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/uri.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/generators/uuid.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/index.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/array.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/boolean.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/index.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/integer.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/null.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/number.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/object.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/string.js
Labels: type: feature, version: 5.x

#8907 feat(samples): add support for contentSchema keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/constants.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/fold-type.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/predicates.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/utils.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/array.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/index.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/string.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8908 feat(examples): add support for examples keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/example.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/fold-type.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/predicates.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/random.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/string.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8909 feat(samples): add support for inferring schema type
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/constants.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/fold-type.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/type.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/types/index.js
Labels: type: feature, version: 5.x

#8910 feat(samples): add support for proper schema merging
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/merge.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
Labels: type: feature, version: 5.x

#8911 refactor(samples): do the general code cleanup
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/type.js
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
Labels: type: enhancement, version: 5.x

#8912 fix(json-schema-2020-12): custom OAS 3.1 formats in type inferrence
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x

#8914 chore(release): prepare configuration for switching to beta channel
  flavors/swagger-ui-react/release/run.sh
  package.json
  swagger-ui-dist-package/deploy.sh
Labels: cat: configuration, version: 5.x

#8906 fix: Add missing swagger-ui-standalone-preset export
  package.json
Labels: type: bug, dependencies, version: 4.x

#8916 feat(samples): add support for merging type keyword
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/core/merge.js
Labels: type: feature, version: 5.x

#8918 chore(deps): bump @babel/runtime-corejs3 from 7.21.5 to 7.22.5
  package-lock.json
  package.json
  test/unit/core/utils.js
Labels: dependencies, version: 4.x

#8922 chore(package-lock): regenerate package-lock.json file
  package-lock.json
  package.json
Labels: dependencies, version: 5.x

#8936 feat(spec): add new specJS selector
  src/core/plugins/err/error-transformers/hook.js
  src/core/plugins/spec/actions.js
  src/core/plugins/spec/selectors.js
Labels: type: feature, version: 5.x

#8937 perf(spec): increase performance of operation expansion
  package-lock.json
  package.json
  src/core/plugins/spec/actions.js
Labels: type: enhancement, version: 5.x
