Repository swagger-api/swagger-ui, pull requests merged in 2023-05, with the labels that each got.

#8609 fix(json-schema-2020-12): enable sub-tree expansion optimization
  src/core/plugins/json-schema-2020-12/hoc.jsx
Labels: cat: performance, version: 5.x

#8610 chore(deps): bump swagger-client from 3.19.6 to 3.19.7
  package-lock.json
  package.json
  webpack/_config-builder.js
Labels: dependencies, version: 5.x

#8612 refactor(json-schema-2020-12): drop optimizeExpansion config option
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/$defs.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AllOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AnyOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentSchemas.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/OneOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/PrefixItems.jsx
  src/core/plugins/json-schema-2020-12/hoc.jsx
Labels: type: enhancement, version: 5.x

#8616 fix(oas31): resolve schemas in 'Schemas section' only if expanded
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/oas31/components/models.jsx
Labels: version: 5.x

#8622 feat(json-schema-2020-12): add support for const keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Const.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8623 feat(json-schema-2020-12): add support for enum keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Enum/Enum.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Enum/_enum.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8625 feat(json-schema-2020-12): add support for validation Keywords for Strings
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/_constraint.scss
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: feature, version: 5.x

#8626 feat(json-schema-2020-12): support validation keywords for arrays
  src/core/plugins/json-schema-2020-12/components/keywords/Contains.jsx
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: feature, version: 5.x

#8628 feat(json-schema-2020-12): add support for required keyword
  src/core/plugins/json-schema-2020-12/components/keywords/Properties/Properties.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Properties/_properties.scss
Labels: type: feature, version: 5.x

#8633 feat(json-schema-2020-12): add support for dependentRequired keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentRequired/DependentRequired.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentRequired/_dependent-required.scss
  src/core/plugins/json-schema-2020-12/components/keywords/Properties/Properties.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Properties/_properties.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8640 feat(json-schema-2020-12): add support for contentMediaType keyword
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: feature, version: 5.x

#8645 feat(json-schema-2020-12): add support for contentSchema keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ContentSchema.jsx
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8646 refactor(json-schema-2020-12): render format keyword as Constraint
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/_constraint.scss
  src/core/plugins/json-schema-2020-12/components/keywords/Format/Format.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Format/_format.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: enhancement, version: 5.x

#8647 feat(json-schema-2020-12): add support for default keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Default.jsx
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8648 feat(json-schema-2020-12): add support for deprecated keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Deprecated/Deprecated.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Deprecated/_deprecated.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: version: 5.x

#8649 feat(json-schema-2020-12): add support for readOnly keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/ReadOnly.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/_read-only.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8650 feat(json-schema-2020-12): add support for writeOnly keyword
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/ReadOnly.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/_read-only.scss
  src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly/WriteOnly.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly/_write-only.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8651 refactor(oas31): standardize JSON Schema 2020-12 plugin extensions
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Description.jsx
Labels: type: enhancement, version: 5.x

#8652 feat(oas31): add support for JSON Schema 2020-12 example keyword
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Description.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Description.jsx
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8656 refactor(json-schema-2020-12): make styles more reusable
  src/core/plugins/json-schema-2020-12/components/keywords/$defs.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/$vocabulary/$vocabulary.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AdditionalProperties.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentSchemas.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Deprecated.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Deprecated/_deprecated.scss
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/ReadOnly/_read-only.scss
  src/core/plugins/json-schema-2020-12/components/keywords/Type.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Type/_type.scss
  src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/WriteOnly/_write-only.scss
  src/core/plugins/json-schema-2020-12/components/keywords/_all.scss
  src/core/plugins/json-schema-2020-12/hoc.jsx
  src/core/plugins/json-schema-2020-12/index.js
Labels: type: enhancement, version: 5.x

#8657 feat(oas31): add support for Schema Object xml keyword
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx
Labels: type: feature, version: 5.x

#8658 feat(oas31): add support for Schema Object discriminator keyword
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/Discriminator.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/DiscriminatorMapping.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Example.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Default.jsx
Labels: type: feature, version: 5.x

#8660 fix(oas31): fix extendable behavior in OpenAPI 3.1 base dialect keywords
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/Discriminator.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/ExternalDocs.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Xml.jsx
Labels: type: enhancement, version: 5.x

#8673 feat(oas31): render JSON Schema 2020-12 in Operations and Webhooks
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Title/Title.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Title/_title.scss
  src/core/plugins/json-schema-2020-12/hooks.js
  src/core/plugins/oas31/components/_all.scss
  src/core/plugins/oas31/components/model/_model.scss
  src/core/plugins/oas31/components/model/model.jsx
  src/core/plugins/oas31/components/models/_models.scss
  src/core/plugins/oas31/components/models/models.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/wrap-components/model.jsx
  src/core/plugins/oas31/wrap-components/models.jsx
  src/core/plugins/oas31/wrap-components/operations.jsx
  src/core/plugins/oas31/wrap-components/webhooks.jsx
  src/style/main.scss
Labels: type: feature, version: 5.x

#8674 fix(json-schema-2020-12): fix rendering of items keywords
  src/core/plugins/json-schema-2020-12/components/keywords/Items.jsx
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x

#8675 feat(oas31): add support for properties keyword includeReadOnly/WriteOnly options
  src/core/plugins/json-schema-2020-12/components/keywords/PatternProperties/PatternProperties.jsx
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Properties.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/wrap-components/keywords/Properties.jsx
  src/core/plugins/oas31/wrap-components/model.jsx
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x

#8680 fix(oas31): fix deep linking for Webhooks and Callbacks
  src/core/plugins/oas3/components/callbacks.jsx
  src/core/plugins/oas31/components/webhooks.jsx
  test/e2e-cypress/tests/features/webhooks.js
Labels: type: bug, version: 5.x

#8689 feat(auth): persist cookie based apiKey in document.cookie
  src/core/plugins/auth/actions.js
  src/core/plugins/auth/configs-extensions/wrap-actions.js
  src/core/plugins/auth/index.js
  src/core/plugins/auth/spec-extensions/wrap-actions.js
  src/core/plugins/auth/wrap-actions.js
  src/core/plugins/configs/actions.js
  test/unit/core/plugins/auth/configs-extensions/wrap-actions.js
  test/unit/core/plugins/auth/spec-extensions/wrap-actions.js
  test/unit/core/plugins/auth/wrap-actions.js
  test/unit/core/plugins/configs/actions.js
Labels: type: feature, version: 4.x

#8692 fix(json-schema-2020-12): fix predicate in hasKeyword function
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x

#8696 docs(swagger-ui-react): hint on usage with nextjs
  flavors/swagger-ui-react/README.md
Labels: cat: documentation, type: enhancement, version: 4.x

#8705 chore(deps-dev): bump sass-loader from 12.6.0 to 13.3.0
  package-lock.json
  package.json
  webpack/stylesheets.babel.js
Labels: dependencies, version: 4.x

#8709 chore(deps): bump swagger-client to v3.19.8
  package-lock.json
  package.json
Labels: dependencies, version: 4.x

#8710 fix(oas31): avoid capitalizing first character of components.schemas
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/oas31/components/models/models.jsx
Labels: type: bug, version: 5.x

#8712 chore(docker): update Dockerfile base image to nginx:1.25.0-alpine
  Dockerfile
Labels: dependencies, version: 4.x, docker

#8731 feat(oas31): enable overrides for samples plugin
  src/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  src/core/plugins/oas31/after-load.js
  src/core/plugins/oas31/fn.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/json-schema-2020-12-extensions/fn.js
  src/core/plugins/oas31/wrap-components/models.jsx
Labels: type: feature, version: 5.x
