Repository swagger-api/swagger-ui, pull requests merged in 2023-08, with the labels that each got.

#9105 feat: respect Encoding Object while building requests
  package-lock.json
  package.json
  src/core/plugins/request-snippets/fn.js
  src/core/window.js
  test/unit/core/curlify.js
Labels: type: bug, version: 5.x

#9106 fix(icons): allow SVG icons to receive arbitrary props
  src/core/plugins/auth/components/lock-auth-icon.jsx
  src/core/plugins/auth/components/lock-auth-operation.jsx
  src/core/plugins/auth/components/lock-auth.jsx
  src/core/plugins/auth/components/unlock-auth-icon.jsx
  src/core/plugins/auth/components/unlock-auth-operation.jsx
  src/core/plugins/auth/components/unlock-auth.jsx
  src/core/plugins/auth/index.js
  src/core/plugins/icons/components/arrow-down.jsx
  src/core/plugins/icons/components/arrow-up.jsx
  src/core/plugins/icons/components/arrow.jsx
  src/core/plugins/icons/components/close.jsx
  src/core/plugins/icons/components/copy.jsx
  src/core/plugins/icons/components/lock.jsx
  src/core/plugins/icons/components/unlock.jsx
Labels: type: regression, version: 5.x

#9110 fix(request-body): access data of request body in safe way
  src/core/plugins/oas3/components/request-body.jsx
Labels: type: bug, version: 5.x

#9111 fix(ui): change copy to clipboard button location
  src/core/components/operation-summary.jsx
  src/style/_buttons.scss
  test/e2e-cypress/e2e/features/external-docs.cy.js
Labels: type: enhancement, cat: user experience, version: 5.x

#8938 feat(syntax-highlighter): add light variant
  docs/usage/configuration.md
  src/core/syntax-highlighting.js
Labels: type: feature, version: 5.x

#9137 fix: allow importing SwaggerUI in Node.js
  .gitignore
  .npmignore
  package.json
Labels: type: regression, version: 5.x

#9141 chore(release): cut the failed v5.4.0 release
  package-lock.json
  package.json
Labels: version: 5.x

#9144 fix(swagger-ui-react): fix corrupted exports field from package.json
  flavors/swagger-ui-react/index.jsx
  flavors/swagger-ui-react/release/create-manifest.js
  flavors/swagger-ui-react/release/run.sh
  flavors/swagger-ui-react/release/template.json
Labels: type: regression, version: 5.x

#9157 docs(README): remove mention about Next.js workaround
  flavors/swagger-ui-react/README.md
Labels: cat: documentation, version: 5.x

#9167 feat: add OpenAPIVersion component
  src/core/components/info.jsx
  src/core/components/openapi-version.jsx
  src/core/plugins/oas3/wrap-components/index.js
  src/core/plugins/oas3/wrap-components/openapi-version.jsx
  src/core/plugins/oas3/wrap-components/version-stamp.jsx
  src/core/plugins/oas31/components/info.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/wrap-components/version-stamp.jsx
  src/core/presets/base.js
  test/e2e-cypress/e2e/features/oas-badge.cy.js
  test/e2e-cypress/e2e/features/urls.cy.js
Labels: type: enhancement, version: 5.x
