Repository swagger-api/swagger-ui, pull requests merged in 2023-07, with the labels that each got.

#9016 docs(swagger-ui-react): fix a typo in README
  flavors/swagger-ui-react/README.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9020 fix: fix critical bug in OpenAPI 3.1.0 resolution
  package-lock.json
  package.json
Labels: type: bug, cat: $ref resolution, version: 5.x

#9021 chore(deps-dev): bump sinon from 15.1.0 to 15.2.0
  config/jest/jest.unit.config.js
  package-lock.json
  package.json
Labels: dependencies, version: 5.x

#9025 fix(swagger-ui-react): fix default value for spec prop
  flavors/swagger-ui-react/index.jsx
Labels: type: bug, version: 5.x

#9030 fix(json-schema-2020-12): fix rendering of exclusiveMin|Max keywords
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x

#9031 fix(json-schema-2020-12): add rendering support for type='integer'
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x

#9032 fix(docker): remove vulnerable libtiff
  Dockerfile
Labels: cat: security, security fix, docker

#9034 fix(docker): fix libtiff NULL Pointer dereference issue
  Dockerfile
Labels: cat: docker, security fix, docker

#9029 feat: Add plugin that wraps icons with React components
  src/core/components/auth/authorization-popup.jsx
  src/core/components/auth/authorize-btn.jsx
  src/core/components/auth/authorize-operation-btn.jsx
  src/core/components/copy-to-clipboard-btn.jsx
  src/core/components/models.jsx
  src/core/components/operation-summary.jsx
  src/core/components/operation-tag.jsx
  src/core/plugins/auth/components/lock-auth-operation.jsx
  src/core/plugins/auth/components/lock-auth.jsx
  src/core/plugins/auth/components/unlock-auth-operation.jsx
  src/core/plugins/auth/components/unlock-auth.jsx
  src/core/plugins/auth/index.js
  src/core/plugins/icons/components/arrow-down.jsx
  src/core/plugins/icons/components/arrow-up.jsx
  src/core/plugins/icons/components/arrow.jsx
  src/core/plugins/icons/components/close.jsx
  src/core/plugins/icons/components/copy.jsx
  src/core/plugins/icons/components/lock.jsx
  src/core/plugins/icons/components/unlock.jsx
  src/core/plugins/icons/index.js
  src/core/plugins/oas31/components/models/models.jsx
  src/core/plugins/request-snippets/request-snippets.jsx
  src/core/presets/base.js
  src/style/_buttons.scss
Labels: type: enhancement, version: 5.x

#9023 fix(json-schema-2020-12): Fix OAS 3.1 additionalProperties false samples
  src/core/plugins/json-schema-2020-12/samples-extensions/fn/main.js
  test/unit/core/plugins/json-schema-2020-12/samples-extensions/fn.js
  test/unit/core/plugins/samples/fn/index.js
Labels: version: 5.x

#9024 docs(setting-up): Fix dev-helper-initializer.js file name
  docs/development/setting-up.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9053 chore(deps): regenerate package-lock.json
  package-lock.json
Labels: dependencies, version: 5.x

#9058 docs(swagger-ui-react): drop claim about no custom plugins support
  flavors/swagger-ui-react/README.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9061 fix(ui): updates `_table.scss` to fix "send empty" checkbox alignment
  src/style/_table.scss
Labels: cat: user experience, cat: a11y, version: 5.x

#8963 fix: alignment of response description column in doc ui
  src/style/_table.scss
Labels: cat: user experience, version: 5.x

#9096 test(curlify): add test for multipart request quotes handling
  test/unit/core/curlify.js
Labels: type: enhancement, version: 5.x
