Repository swagger-api/swagger-ui, pull requests merged in 2023-04, with the labels that each got.

#8546 Merge with master branch
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, version: 5.x

#8547 fix(oas31): fix rendering Path Items containing schemas with cycles
  package-lock.json
  package.json
Labels: type: bug, version: 5.x

#8579 fix: remove download button when content is empty
  src/core/components/response-body.jsx
  test/unit/components/response-body.jsx
  test/unit/setup.js
Labels: type: bug, version: 4.x
