Repository swagger-api/swagger-ui, pull requests merged in 2023-03, with the labels that each got.

#8431 feat: integrate swagger-client@3.19.0-beta.8
  package-lock.json
  package.json
Labels: type: enhancement, dependencies, version: 4.x

#8440 fix(docker): use vulnerability free Node.js=>18.14.1-r0
  Dockerfile
Labels: cat: security, security fix, docker

#8445 chore(deps): update swagger-client to v3.19.0
  package-lock.json
  package.json
Labels: type: enhancement, dependencies, version: 4.x

#8438 fix(docker): add missing ipv6 all-interfaces binding
  docker/nginx.conf
Labels: type: enhancement, version: 4.x, docker

#8436 feat(swagger-ui-react): add showCommonExtensions option
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
Labels: type: feature, version: 4.x

#8453 chore(deps): update swagger-client from v3.19.0 to v3.19.1
  package.json
Labels: dependencies, javascript

#8454 chore(deps): update swagger-client from v3.19.0 to v3.19.1
  package-lock.json
Labels: dependencies, javascript

#8455 ci(nodejs): run workflow on next branch
  .github/workflows/nodejs.yml
Labels: type: enhancement

#8456 test(core): fix unit test assertion
  test/unit/core/utils.js
Labels: type: enhancement

#8460 build(webpack): amend build configs to compensate for ApiDOM
  package-lock.json
  package.json
  webpack/_config-builder.js
Labels: type: enhancement, dependencies, version: 5.x

#8468 ci(release): prepare configs for v5 alpha pre-releases
  package.json
Labels: type: enhancement, version: 5.x, CICD

#8400 Decode model schema name on model component
  src/core/components/model.jsx
  test/unit/core/helpers/get-model-name.js
Labels: type: enhancement, version: 4.x

#8476 refactor(oas31): change License component into smart
  src/core/plugins/oas3/spec-extensions/selectors.js
  src/core/plugins/oas3/spec-extensions/wrap-selectors.js
  src/core/plugins/oas31/components/license.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/selectors.js
  src/core/plugins/oas31/spec-extensions/selectors.js
  src/core/plugins/oas31/wrap-components/license.jsx
Labels: type: enhancement, version: 5.x

#8478 refactor(oas31): change Contact component to be smart
  src/core/plugins/oas31/components/contact.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/spec-extensions/selectors.js
  src/core/plugins/oas31/wrap-components/contact.jsx
Labels: type: enhancement, version: 5.x

#8479 refactor(oas31): change Info compnent to be smart
  src/core/plugins/oas31/components/info.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/spec-extensions/selectors.js
  src/core/plugins/oas31/wrap-components/info.jsx
Labels: type: enhancement, version: 5.x

#8481 refactor(oas31): simplify Webhooks component by utilizing selectors
  src/core/components/layouts/base.jsx
  src/core/components/operations.jsx
  src/core/plugins/oas3/selectors.js
  src/core/plugins/oas3/spec-extensions/wrap-selectors.js
  src/core/plugins/oas31/components/webhooks.jsx
  src/core/plugins/oas31/helpers.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/spec-extensions/selectors.js
  src/core/plugins/oas31/spec-extensions/wrap-selectors.js
  src/core/plugins/spec/selectors.js
  test/unit/components/operations.jsx
Labels: type: enhancement, version: 5.x

#8484 refactor(oas31): introduce selector composition mechanism
  src/core/plugins/oas31/fn.js
  src/core/plugins/oas31/helpers.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/selectors.js
  src/core/plugins/oas31/spec-extensions/selectors.js
  src/core/plugins/oas31/spec-extensions/wrap-selectors.js
Labels: type: enhancement, version: 5.x

#8485 refactor(oas31): disable try it out mechanism explicitly for webhooks
  src/core/plugins/oas3/components/request-body.jsx
  src/core/plugins/oas31/fn.js
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/oas3-extensions/wrap-selectors.js
  src/core/plugins/oas31/spec-extensions/wrap-selectors.js
Labels: type: enhancement, version: 5.x

#8496 feat(oas31): add support for rendering OpenAPI.jsonSchemaDialect field
  src/core/plugins/oas31/components/info.jsx
  src/core/plugins/oas31/components/json-schema-dialect.jsx
  src/core/plugins/oas31/index.js
  src/core/plugins/oas31/spec-extensions/selectors.js
Labels: type: feature, version: 5.x

#8499 fix(oas31): fix recursive bug in hasUserEditedBody selector wrapper
  src/core/plugins/oas31/fn.js
  src/core/plugins/oas31/oas3-extensions/wrap-selectors.js
Labels: type: enhancement, version: 5.x

#8500 fix(oas31): detect user request body edits in OpenAPI.paths
  src/core/plugins/oas31/fn.js
  src/core/plugins/oas31/oas3-extensions/wrap-selectors.js
  src/core/plugins/oas31/spec-extensions/wrap-selectors.js
Labels: type: bug, version: 5.x

#8507 fix(oas31): display Callback operations only
  src/core/plugins/oas3/components/callbacks.jsx
  src/core/plugins/oas3/spec-extensions/selectors.js
  src/core/plugins/oas31/spec-extensions/selectors.js
Labels: type: bug, version: 5.x

#8512 test(core): align test with dependency update
  package-lock.json
  package.json
  test/unit/core/utils.js
Labels: type: enhancement, version: 5.x

#8526 chore(dist-tags): use alpha npm dist tags for 5.x.y-alpha.* releases
  flavors/swagger-ui-react/release/run.sh
  swagger-ui-dist-package/deploy.sh
Labels: type: enhancement, version: 5.x

#8533 fix: add relative reference support for baseDoc option
  package-lock.json
  package.json
Labels: type: bug, version: 5.x

#8534 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies, version: 4.x

#8536 fix(oas31): fix resolver error about immutable Headers
  package-lock.json
  package.json
Labels: type: bug, dependencies, version: 5.x
