Repository swagger-api/swagger-ui, pull requests merged in 2023-11, with the labels that each got.

#9361 Fix: remove redundant aria-label from accordion button
  src/core/components/operation-summary.jsx
Labels: type: enhancement, cat: a11y, version: 5.x

#9343 fix: missing download button
  src/core/components/response-body.jsx
  test/unit/components/response-body.jsx
Labels: type: regression, version: 5.x

#9329 fix: update custom-layout.md
  docs/customization/custom-layout.md
Labels: cat: documentation, type: enhancement, version: 5.x

#8169 ci: add minimum GitHub token permissions for workflows
  .github/workflows/dependabot-merge.yml
  .github/workflows/docker-image-check.yml
  .github/workflows/nodejs.yml
Labels: type: enhancement, version: 5.x, CICD

#9325 Fix(styling): Make the Swagger UI Operation page more responsive on smaller screen
  src/core/components/operation-summary.jsx
  src/style/_layout.scss
  src/style/_topbar.scss
Labels: type: enhancement, cat: a11y, version: 5.x

#9153 refactor(oas31): use system.fn as source of truth for all components
  src/core/plugins/oas31/wrap-components/model.jsx
Labels: type: bug, version: 5.x

#9246 Add base64-url content encoding
  src/core/plugins/json-schema-2020-12-samples/fn/class/EncoderRegistry.js
  src/core/plugins/json-schema-2020-12-samples/fn/encoders/base64url.js
  test/unit/core/plugins/json-schema-2020-12-samples/fn.js
Labels: type: feature, version: 5.x

#9387 Fix(styling): Ensure authorize button stays on the right for UX reasons
  src/core/components/layouts/base.jsx
  src/style/_layout.scss
Labels: type: regression, version: 5.x

#9399 chore(release): manual release bump to v5.10.1
  package-lock.json
  package.json
Labels: type: enhancement, version: 5.x

#9390 fix: make input HTML IDs unique in authorization-popup.jsx
  src/core/components/auth/oauth2.jsx
  test/e2e-cypress/e2e/features/auth-code-flow-pkce-without-secret.cy.js
  test/e2e-cypress/e2e/features/oauth2-flows/application.cy.js
  test/e2e-cypress/e2e/features/oauth2-flows/password.cy.js
  test/e2e-cypress/e2e/security/sequential-import-chaining.cy.js
Labels: type: enhancement, cat: a11y, version: 5.x
