Repository swagger-api/swagger-ui, pull requests merged in 2024-11, with the labels that each got.

#10192 chore(docker): remove explicit Node.js install
  Dockerfile
Labels: type: enhancement, cat: docker, docker

#10193 chore(deps): update swagger-client to v3.30.1
  package-lock.json
  package.json
  webpack/dev-e2e.js
Labels: type: enhancement, dependencies, version: 5.x

#10194 feat(analytics): use Scarf.js to provide anonymized installation analytics
  README.md
  flavors/swagger-ui-react/README.md
  package-lock.json
  package.json
  swagger-ui-dist-package/README.md
  swagger-ui-dist-package/package.json
Labels: type: enhancement, dependencies, version: 5.x

#10203 chore(docker): disable apk cache
  Dockerfile
Labels: type: enhancement, cat: docker, docker, version: 5.x

#10204 fix: update Scarf.js to v1.4.0 to avoid breaking Vitest
  package-lock.json
  package.json
Labels: type: integration bug, dependencies, version: 5.x

#10205 chore(dist): update Scarf.js to v1.4.0
  swagger-ui-dist-package/package.json
Labels: type: enhancement, dependencies, version: 5.x
