Repository swagger-api/swagger-ui, pull requests merged in 2024-05, with the labels that each got.

#9906 docs: Add missing `npm install` in the development docs
  docs/development/setting-up.md
Labels: cat: documentation, type: enhancement

#9909 fix(security): remove patch-package production dependency
  package-lock.json
  package.json
  patches/tachyons-sass+4.9.5.patch
Labels: cat: security, version: 5.x

#9914 fix(try-it-out): fix parsing null values when building requests
  package-lock.json
  package.json
Labels: type: bug, cat: try-it-out, version: 5.x

#9917 refactor(config): fix naming of system options
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9918 fix(swagger-ui-react): display definition defined as YAML or JSON string
  flavors/swagger-ui-react/index.jsx
Labels: type: regression, version: 5.x

#9919 fix(system): allow wrapping components both from presets and plugins
  docs/customization/plugin-api.md
  docs/usage/configuration.md
  src/core/config/defaults.js
  src/core/config/factorization/system.js
  src/core/config/type-cast/mappings.js
  src/core/system.js
  test/unit/core/system/wrapComponent.jsx
Labels: type: bug, version: 5.x

#9926 fix(components): fix rendering for empty examples in responses
  src/core/components/response.jsx
  test/e2e-cypress/e2e/features/response-empty-examples-object.cy.js
  test/e2e-cypress/static/documents/features/response-empty-examples-object.yaml
Labels: type: bug, version: 5.x

#9930 fix(deps): allow to consolidate deps in downstream projects
  package-lock.json
  package.json
Labels: type: regression, dependencies

#9934 fix(components): add support for oneOf/anyOf JSON Schema keywords in parameter-row rendering
  src/core/components/parameter-row.jsx
  test/e2e-cypress/e2e/features/parameters-one-of-any-of.cy.js
  test/e2e-cypress/static/documents/features/parameters-one-of-any-of-oas3.yaml
  test/e2e-cypress/static/documents/features/parameters-one-of-any-of-oas31.yaml
  test/unit/bugs/4557-default-parameter-values.jsx
  test/unit/components/parameter-row.jsx
Labels: type: bug, version: 5.x

#9938 fix(oas31): fix re-rendering of the Webhooks component
  src/core/plugins/oas31/components/webhooks.jsx
  src/core/plugins/oas31/spec-extensions/selectors.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-webhook-examples.cy.js
  test/e2e-cypress/static/documents/features/oas31-webhook-examples.yaml
Labels: type: bug, specification: 3.x, version: 5.x

#9950 fix(swagger-client): fix OpenAPI 3.1.0 dereferencing
  package-lock.json
  package.json
Labels: swagger-js, type: regression, version: 5.x

#9949 fix(config): define missing default options
  src/core/config/defaults.js
  src/core/config/type-cast/mappings.js
  src/core/config/type-cast/type-casters/function.js
  src/core/config/type-cast/type-casters/nullable-function.js
  src/core/config/type-cast/type-casters/sorter.js
  src/core/plugins/request-snippets/fn.js
Labels: type: bug, cat: configuration

#9957 docs(SECURITY): align supported versions with reality
  SECURITY.md
Labels: cat: documentation, cat: security

#9958 refactor(config): remove unused config options
  src/core/config/defaults.js
  src/core/config/factorization/inline-plugin.js
Labels: type: enhancement, version: 5.x

#9966 fix(swagger-ui-react): re-render on spec property change
  flavors/swagger-ui-react/index.jsx
Labels: type: regression, version: 5.x

#9975 ci(dependabot): use times that don't conflict with releases
  .github/dependabot.yaml
Labels: version: 5.x, CICD
