Repository swagger-api/swagger-ui, pull requests merged in 2024-04, with the labels that each got.

#9784 refactor(syntax-highlighting): use component wrapping for syntax highlighting activation
  src/core/components/curl.jsx
  src/core/components/example.jsx
  src/core/components/model-example.jsx
  src/core/components/param-body.jsx
  src/core/components/response-body.jsx
  src/core/components/response.jsx
  src/core/plugins/oas3/components/request-body.jsx
  src/core/plugins/request-snippets/request-snippets.jsx
  src/core/plugins/syntax-highlighting/components/HighlightCode.jsx
  src/core/plugins/syntax-highlighting/components/PlainTextViewer.jsx
  src/core/plugins/syntax-highlighting/components/SyntaxHighlighter.jsx
  src/core/plugins/syntax-highlighting/index.js
  src/core/plugins/syntax-highlighting/wrap-components/SyntaxHighlighter.jsx
  src/style/_layout.scss
  test/unit/components/highlight-code.jsx
Labels: cat: plugins, type: enhancement, version: 5.x

#9786 fix(docker): fix CVE-2024-27983 related to Node.js
  Dockerfile
Labels: cat: security, docker, version: 5.x

#9787 fix(oas31): allow override names of top level schemas
  src/core/plugins/json-schema-2020-12/components/keywords/Title/Title.jsx
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/oas31/components/models/models.jsx
  test/e2e-cypress/e2e/features/plugins/json-schema-2020-12/schema-title.cy.js
  test/e2e-cypress/static/documents/features/json-schema-2020-12-title.yaml
Labels: type: enhancement, version: 5.x

#9795 feat(json-schema-2020-12-sample): introduce option API
  src/core/plugins/json-schema-2020-12-samples/fn/api/optionAPI.js
  src/core/plugins/json-schema-2020-12-samples/fn/class/OptionRegistry.js
  src/core/plugins/json-schema-2020-12-samples/fn/index.js
  src/core/plugins/json-schema-2020-12-samples/index.js
Labels: type: enhancement, version: 5.x

#9796 fix(json-schema-2020-12-samples): apply string constraints sensibly
  src/core/plugins/json-schema-2020-12-samples/fn/types/string.js
Labels: type: enhancement, version: 5.x

#9794 fix(oas3): merge schema with schema unresolved by swagger-client
  src/core/components/model.jsx
  test/e2e-cypress/e2e/features/plugins/oas3/all-of-circular-ref.cy.js
  test/e2e-cypress/static/documents/features/oas3-all-of-circular-ref.yaml
Labels: type: regression, specification: 3.x, version: 5.x

#9776 fix(docs): fix wrong syntaxHighlight property
  docs/usage/configuration.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9798 refactor: consolidate all JSON Schema 5 rendering code into json-schema-5 plugin
  src/core/index.js
  src/core/plugins/json-schema-5/components/array-model.jsx
  src/core/plugins/json-schema-5/components/enum-model.jsx
  src/core/plugins/json-schema-5/components/json-schema-components.jsx
  src/core/plugins/json-schema-5/components/model-collapse.jsx
  src/core/plugins/json-schema-5/components/model-example.jsx
  src/core/plugins/json-schema-5/components/model-wrapper.jsx
  src/core/plugins/json-schema-5/components/model.jsx
  src/core/plugins/json-schema-5/components/models.jsx
  src/core/plugins/json-schema-5/components/object-model.jsx
  src/core/plugins/json-schema-5/components/primitive-model.jsx
  src/core/plugins/json-schema-5/components/schemes.jsx
  src/core/plugins/json-schema-5/containers/schemes.jsx
  src/core/plugins/json-schema-5/index.js
  src/core/plugins/oas3/wrap-components/model.jsx
  src/core/presets/base/index.js
  src/core/presets/base/plugins/core-components/index.js
  src/core/presets/base/plugins/json-schema-components/index.js
  test/unit/core/helpers/get-model-name.js
  test/unit/core/plugins/json-schema-5/components/json-schema-form.jsx
  test/unit/core/plugins/json-schema-5/components/model-example.jsx
  test/unit/core/plugins/json-schema-5/components/models.jsx
  test/unit/core/plugins/json-schema-5/components/object-model.jsx
  test/unit/core/plugins/json-schema-5/components/primitive-model.jsx
  test/unit/core/plugins/json-schema-5/components/response.jsx
  test/unit/core/plugins/json-schema-5/components/schemes-wrapper.jsx
  test/unit/core/plugins/json-schema-5/components/schemes.jsx
Labels: type: enhancement, version: 5.x

#9775 fix(spec): format validation errors for nested parameters
  src/core/plugins/spec/selectors.js
  test/unit/core/plugins/spec/selectors.js
Labels: type: bug, cat: plugins

#9799 refactor(json-schema-2020-12-samples): design formatAPI consistent with mediatypeAPI and encoderAPI
  src/core/plugins/json-schema-2020-12-samples/fn/api/formatAPI.js
  src/core/plugins/json-schema-2020-12-samples/fn/class/FormatRegistry.js
  src/core/plugins/json-schema-2020-12-samples/fn/types/number.js
  src/core/plugins/json-schema-2020-12-samples/fn/types/string.js
Labels: type: enhancement, version: 5.x

#9805 fix(try-it-out): fix objects in arrays being stringified twice when building requests
  package-lock.json
  package.json
Labels: type: bug, specification: 3.x, version: 5.x

#9809 fix(utils): make URL search params parsing and serialization WHATWG URL compliant
  src/core/utils/index.js
  test/unit/core/utils.js
Labels: type: enhancement, version: 5.x

#9802 chore: fix some typos in comments
  test/unit/core/plugins/err/transformers/not-of-type.js
  test/unit/core/plugins/err/transformers/parameter-oneof.js
Labels: type: enhancement, version: 5.x

#9815 refactor(config): disect & compose
  src/core/config/defaults.js
  src/core/config/factorization/inline-plugin.js
  src/core/config/factorization/store.js
  src/core/config/index.js
  src/core/config/merge.js
  src/core/config/sources/query.js
  src/core/config/sources/system.js
  src/core/config/sources/url.js
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9811 refactor: consolidate configuration code into config
  src/core/config/defaults.js
  src/core/config/factorization/inline-plugin.js
  src/core/config/factorization/store.js
  src/core/config/index.js
  src/core/config/merge.js
  src/core/config/sources/query.js
  src/core/config/sources/system.js
  src/core/config/sources/url.js
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9820 feat: expose build info via new versions plugin
  src/core/index.js
  src/core/plugins/versions/after-load.js
  src/core/plugins/versions/index.js
  src/core/presets/base/index.js
Labels: type: enhancement, version: 5.x

#9824 fix(config): handle query config options
  src/core/config/merge.js
  src/core/config/sources/query.js
  src/standalone/plugins/top-bar/components/TopBar.jsx
Labels: type: bug, version: 5.x

#9826 feat(request-snippets): use active class modifier for active snippet
  src/core/plugins/request-snippets/request-snippets.jsx
Labels: type: enhancement, version: 5.x

#9834 add github url in readme links
  README.md
Labels: cat: documentation, type: enhancement

#9839 style(request-snippets): change name of active class
  src/core/plugins/request-snippets/request-snippets.jsx
Labels: type: enhancement, cat: customization, version: 5.x

#9829 fix(config): cast configuration values into proper types
  flavors/swagger-ui-react/index.jsx
  src/core/components/live-response.jsx
  src/core/components/operation-tag.jsx
  src/core/config/defaults.js
  src/core/config/factorization/store.js
  src/core/config/merge.js
  src/core/config/type-cast/index.js
  src/core/config/type-cast/mappings.js
  src/core/config/type-cast/type-casters/array.js
  src/core/config/type-cast/type-casters/boolean.js
  src/core/config/type-cast/type-casters/dom-node.js
  src/core/config/type-cast/type-casters/filter.js
  src/core/config/type-cast/type-casters/nullable-array.js
  src/core/config/type-cast/type-casters/nullable-string.js
  src/core/config/type-cast/type-casters/number.js
  src/core/config/type-cast/type-casters/object.js
  src/core/config/type-cast/type-casters/string.js
  src/core/config/type-cast/type-casters/syntax-highlight.js
  src/core/config/type-cast/type-casters/undefined-string.js
  src/core/containers/OperationContainer.jsx
  src/core/containers/filter.jsx
  src/core/plugins/layout/spec-extensions/wrap-selector.js
  src/core/plugins/swagger-client/configs-wrap-actions.js
  src/core/plugins/syntax-highlighting/components/SyntaxHighlighter.jsx
  src/core/plugins/syntax-highlighting/wrap-components/SyntaxHighlighter.jsx
  test/unit/components/filter.jsx
  test/unit/core/config/type-cast/index.js
  test/unit/core/plugins/swagger-js/withCredentials.js
Labels: type: bug, version: 5.x

#9840 fix(config): address getting configUrl from options
  src/core/config/defaults.js
  src/core/config/sources/query.js
  src/core/config/type-cast/mappings.js
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9843 fix(config): sync SwaggerUI default options with swagger-ui-react
  flavors/swagger-ui-react/index.jsx
  src/core/index.js
Labels: type: enhancement, version: 5.x

#9845 fix(config): add options defined during runtime
  src/core/config/defaults.js
  src/core/config/index.js
  src/core/config/sources/runtime.js
  src/core/index.js
Labels: type: regression, version: 5.x

#9847 fix(swagger-ui-react): avoid triggering implicit system rendering
  flavors/swagger-ui-react/index.jsx
Labels: type: regression, version: 5.x

#9848 style(core): apply prettier formatting
  src/core/index.js
Labels: type: enhancement, cat: style & presentation, version: 5.x

#9841 chore: fix some typos in comments
  src/core/plugins/json-schema-2020-12-samples/fn/main.js
  src/core/plugins/json-schema-5-samples/fn/index.js
Labels: cat: documentation, type: enhancement, version: 5.x

#9854 refactor(config): export config options typecasing mechanism
  src/core/config/index.js
Labels: type: enhancement, version: 5.x

#9855 feat(swagger-ui-react): rewrite into SSR compatible function component
  flavors/swagger-ui-react/index.jsx
Labels: type: enhancement, version: 5.x

#9863 fix(utils): fix validation for required parameters without specified type
  src/core/utils/index.js
  test/unit/core/utils.js
Labels: type: bug, version: 5.x

#9853 fix(json-schema-2020-12-samples): skip anyOf and oneOf while merging schemas
  src/core/plugins/json-schema-2020-12-samples/fn/main.js
  test/unit/core/plugins/json-schema-2020-12-samples/fn.js
Labels: type: bug, version: 5.x

#9875 fix(config): remove system config source
  docs/usage/configuration.md
  flavors/swagger-ui-react/index.jsx
  src/core/config/index.js
  src/core/config/sources/system.js
  src/core/config/sources/url.js
  src/core/index.js
  src/core/plugins/configs/actions.js
  src/core/plugins/configs/fn.js
  src/core/plugins/configs/index.js
  src/core/plugins/configs/spec-actions.js
  swagger-config.yaml
  test/unit/core/plugins/configs/actions.js
Labels: type: bug, cat: configuration, version: 5.x

#9877 fix(webpack): enable SourceMaps in releases
  .npmignore
  flavors/swagger-ui-react/release/run.sh
  webpack/_config-builder.js
  webpack/_helpers.js
  webpack/bundle.js
  webpack/es-bundle-core.js
  webpack/es-bundle.js
  webpack/standalone.js
Labels: type: bug, version: 5.x

#9895 fix(swagger-ui-react): call onComplete hook with system instance
  flavors/swagger-ui-react/index.jsx
Labels: type: bug, version: 5.x
