Repository swagger-api/swagger-ui, pull requests merged in 2024-03, with the labels that each got.

#9664 fix(oas31): render responses that do not have content field
  src/core/components/response.jsx
  src/core/plugins/json-schema-2020-12-samples/fn/main.js
  src/core/plugins/oas31/after-load.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-empty-content.cy.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-empty-media-type.cy.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-response-no-content.cy.js
  test/e2e-cypress/static/configs/oas31-response-no-content.yaml
  test/e2e-cypress/static/documents/features/oas31-response-empty-content.yaml
  test/e2e-cypress/static/documents/features/oas31-response-empty-media-type.yaml
  test/e2e-cypress/static/documents/features/oas31-response-no-content.yaml
Labels: type: bug, version: 5.x

#9667 fix: avoid rendering empty response schemas
  src/core/components/model-example.jsx
  test/e2e-cypress/e2e/features/default-model-rendering.cy.js
  test/e2e-cypress/static/documents/features/default-model-rendering.yaml
Labels: type: bug, cat: rendering, version: 5.x

#9668 refactor(components): rewrite ModelExample into functional component
  src/core/components/model-example.jsx
Labels: type: enhancement, version: 5.x

#9179 Limit Curl Example to height of 400px.
  src/style/_layout.scss
Labels: type: enhancement, cat: style & presentation

#9688 ci: add CodeQL SAST workflow
  .github/workflows/codeql.yml
Labels: cat: security, type: enhancement, CICD

#9689 ci: set ignore paths for CodeSQL SAST
  .github/workflows/codeql.yml
Labels: cat: security, type: enhancement

#9687 fix(spec): validation errors formatting
  src/core/plugins/spec/selectors.js
  test/unit/core/plugins/spec/selectors.js
Labels: type: bug, cat: plugins

#9691 fix(oas3): escape regular expression before using it
  src/core/plugins/oas3/selectors.js
Labels: type: bug, cat: security, version: 5.x

#9692 fix(request-snipppets): fix issues in escaping Powershell
  src/core/plugins/request-snippets/fn.js
Labels: cat: security, security fix, version: 5.x

#9746 fix(try-it-out): fix issues related to building requests from parameters
  package-lock.json
  package.json
Labels: type: bug, swagger-js, cat: try-it-out

#9764 chore: remove repetitive word in docs
  docs/usage/configuration.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9766 feat(plugins): expose JSON Schema merging mechanism from samples plugins
  src/core/plugins/json-schema-2020-12-samples/fn/index.js
  src/core/plugins/json-schema-2020-12-samples/index.js
  src/core/plugins/json-schema-5-samples/fn/index.js
  src/core/plugins/json-schema-5-samples/index.js
  src/core/plugins/oas31/after-load.js
  test/unit/core/plugins/json-schema-2020-12-samples/fn.js
  test/unit/core/plugins/json-schema-5-samples/fn/index.js
Labels: type: feature, cat: plugins

#9762 fix(oas3): fix getting initial values for request body in OpenAPI 3.x
  src/core/plugins/oas3/components/request-body.jsx
  test/e2e-cypress/e2e/features/oas3-request-body-allow-empty-values.cy.js
  test/e2e-cypress/e2e/features/oas3-request-body-required.cy.js
  test/e2e-cypress/e2e/features/plugins/oas3/one-of-any-of-example.cy.js
  test/e2e-cypress/static/documents/features/oas3-one-of-any-of-example.yaml
Labels: type: bug, specification: 3.x, cat: try-it-out

#9767 fix(oas3): add support for oneOf/anyOf JSON Schema keywords in request-body rendering
  src/core/plugins/oas3/components/request-body.jsx
  test/e2e-cypress/e2e/features/plugins/oas3/one-of-any-of-example.cy.js
  test/e2e-cypress/static/documents/features/oas3-one-of-any-of-example.yaml
Labels: type: bug, specification: 3.x
