Repository swagger-api/swagger-ui, pull requests merged in 2024-02, with the labels that each got.

#9555 fix(spec): render response body for non-200 responses
  src/core/plugins/spec/actions.js
  src/core/plugins/spec/reducers.js
  test/e2e-cypress/e2e/features/try-it-out-non-200-response-body.cy.js
  test/e2e-cypress/static/documents/features/try-it-out-non-200-response-body.yaml
Labels: type: bug, version: 5.x

#9489 docs: update `unpkg` installation to use latest version
  docs/usage/installation.md
Labels: cat: documentation, type: enhancement, version: 5.x

#9563 fix: add missing HTML id attributes
  src/core/components/schemes.jsx
  src/core/plugins/oas3/components/servers.jsx
  src/standalone/plugins/top-bar/components/TopBar.jsx
Labels: type: bug, cat: a11y, version: 5.x

#9567 fix(spec): set multi-value parameters as an immutable list
  src/core/plugins/spec/reducers.js
  test/unit/core/plugins/spec/reducer.js
Labels: type: bug, cat: plugins

#9581 fix(json-schema-2020-12): defaultModelExpandDepth not expanding schemas
  src/core/plugins/json-schema-2020-12/components/keywords/$defs.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/$vocabulary/$vocabulary.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AllOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AnyOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentSchemas.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/OneOf.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/PrefixItems.jsx
  test/e2e-cypress/e2e/features/plugins/json-schema-2020-12/expansion.cy.js
  test/e2e-cypress/static/pages/json-schema-2020-12-expansion/expansion.yaml
  test/e2e-cypress/static/pages/json-schema-2020-12-expansion/index.html
Labels: type: bug, cat: plugins

#9588 test: consolidate unit tests
  .eslintignore
  .eslintrc
  .github/workflows/nodejs.yml
  .mocharc.yaml
  config/jest/jest.unit.config.js
  docs/development/scripts.md
  package.json
  test/.eslintrc
  test/components/response-body.jsx
  test/mocha/.eslinrc
  test/mocha/components/live-response.jsx
  test/mocha/components/online-validator-badge.jsx
  test/mocha/setup.js
  test/mocha/xss/anchor-target-rel/online-validator-badge.jsx
  test/unit/.eslintrc
  test/unit/components/highlight-code.jsx
  test/unit/components/live-response.jsx
  test/unit/components/online-validator-badge.jsx
  test/unit/xss/anchor-target-rel/online-validator-badge.jsx
Labels: type: enhancement, version: 5.x

#9589 chore(deps-dev): bump webpack-dev-server from 4.15.1 to 5.0.1
  package-lock.json
  package.json
Labels: dependencies, version: 5.x

#9511 fix(spec): ignore empty string for multi-value parameter
  src/core/plugins/spec/selectors.js
  test/unit/core/plugins/spec/selectors.js
Labels: type: bug, cat: try-it-out

#9600 fix(docker): fix libexpat vulnerability
  Dockerfile
Labels: security fix, docker

#9601 fix(docker): fix libexpat vulnerability
  Dockerfile
Labels: cat: security, security fix, docker

#9602 fix(docker): fix libexpat vulnerability
  Dockerfile
Labels: cat: security, cat: docker, security fix, docker

#9604 ci(dependabot): auto-update GitHub Actions
  .github/dependabot.yaml
Labels: type: enhancement, dependencies, CICD

#9629 fix: resolve unresolved schemas
  src/core/components/model.jsx
  src/core/components/object-model.jsx
  src/core/plugins/oas3/spec-extensions/selectors.js
  src/core/plugins/oas3/spec-extensions/wrap-selectors.js
  test/e2e-cypress/e2e/features/plugins/oas3/complex-spec.cy.js
  test/e2e-cypress/static/documents/features/oas3-complex-spec.json
  test/unit/core/plugins/oas3/selectors.js
Labels: type: bug, cat: $ref resolution
