Repository swagger-api/swagger-ui, pull requests merged in 2024-01, with the labels that each got.

#9454 chore(deps): bump swagger-client from v3.24.6 to v3.25.0
  package-lock.json
  package.json
Labels: dependencies

#9453 fix: React warnings of "Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."
  src/core/components/errors.jsx
  src/core/components/highlight-code.jsx
  src/core/components/providers/markdown.jsx
  src/core/plugins/icons/components/arrow-down.jsx
  src/core/plugins/icons/components/arrow-up.jsx
  src/core/plugins/icons/components/arrow.jsx
  src/core/plugins/icons/components/close.jsx
  src/core/plugins/icons/components/copy.jsx
  src/core/plugins/icons/components/lock.jsx
  src/core/plugins/icons/components/unlock.jsx
  src/core/plugins/json-schema-2020-12/components/Accordion/Accordion.jsx
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Title/Title.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Type.jsx
  src/core/plugins/oas3/wrap-components/markdown.jsx
  src/core/plugins/oas31/json-schema-2020-12-extensions/components/keywords/Discriminator/DiscriminatorMapping.jsx
Labels: type: enhancement, cat: rendering

#9465 fix(swagger-ui-react): align React versions with swagger-ui
  flavors/swagger-ui-react/release/template.json
Labels: type: bug, version: 5.x

#9470 chore(deps-dev): update release-it to latest version
  .github/dependabot.yaml
  package-lock.json
  package.json
Labels: version: 5.x

#9519 fix(oas31): make selectors always return expected shapes
  src/core/plugins/oas31/spec-extensions/selectors.js
Labels: type: bug, version: 5.x

#9520 fix(docker): disallow embedding SwaggerUI served from docker by default
  Dockerfile
  docker/default.conf.template
  docker/docker-entrypoint.d/40-swagger-ui.sh
  docker/embedding.conf
Labels: cat: security, security fix, docker, version: 5.x
