Repository swagger-api/swagger-ui, pull requests merged in 2025-06, with the labels that each got.

#10329 Exclude large obsolete directories from publishing to Packagist
  .gitattributes
Labels: type: enhancement, version: 5.x

#10488 ft(oas3): show the schema tab in the Try it Out mode
  src/core/plugins/oas3/components/request-body.jsx
  test/e2e-cypress/e2e/features/schema-rendering.cy.js
Labels: type: feature, type: enhancement, version: 5.x

#10491 ci(docker): build and publish unstable docker image
  .github/workflows/docker-build-push-unstable.yml
Labels: type: enhancement, cat: docker, docker, version: 5.x, CICD

#10493 ci: drop old unused workflows
  .github/workflows/release-swagger-ui-react.yml
  .github/workflows/release-swagger-ui.yml
Labels: type: enhancement, version: 5.x, CICD

#10494 ci(swagger-ui-release): add GA workflow for release
  .github/workflows/swagger-ui-release.yml
Labels: type: enhancement, version: 5.x, CICD

#10495 ci(swagger-ui-react-release): add GA workflow for release
  .github/workflows/release-swagger-ui-react.yml
Labels: type: enhancement, CICD

#10497 fix: align expanded content inside expand collapse button
  src/style/_table.scss
Labels: type: enhancement, version: 5.x
