Repository swagger-api/swagger-ui, pull requests merged in 2025-05, with the labels that each got.

#10453 fix: avoid accessing properties of empty Example Objects
  src/core/components/examples-select-value-retainer.jsx
Labels: type: bug, version: 5.x

#10454 fix(spec): assure operation is an immutable map in operations selectors
  src/core/plugins/spec/selectors.js
Labels: type: bug, version: 5.x

#10457 fix: assure parameter is an immutable map when grouping parameters
  src/core/components/parameters/parameters.jsx
Labels: type: bug, version: 5.x

#10456 fix(spec): avoid accessing $ref when path item is not an object
  src/core/plugins/spec/wrap-actions.js
Labels: type: bug, version: 5.x

#10459 fix(json-schema-2020-12-samples): generate proper samples for XML atttributes
  src/core/plugins/json-schema-2020-12-samples/fn/main.js
  src/core/plugins/json-schema-2020-12-samples/fn/types/array.js
  test/unit/core/plugins/json-schema-2020-12-samples/fn.js
Labels: type: bug, version: 5.x, specification: 3.1

#10460 fix(security): update Axios to non-vulnerable 1.9.0 version
  package-lock.json
  package.json
Labels: dependencies

#10462 feat(observability): allow defining custom uncaught exception handler
  flavors/swagger-ui-react/README.md
  flavors/swagger-ui-react/index.jsx
  src/core/config/defaults.js
  src/core/config/type-cast/mappings.js
  src/core/system.js
Labels: type: enhancement
