Repository swagger-api/swagger-ui, pull requests merged in 2025-04, with the labels that each got.

#10397 fix(json-schema-2020-12): avoid accessing properties of null schemas
  src/core/plugins/json-schema-2020-12/components/JSONSchema/JSONSchema.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/AdditionalProperties.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/Constraint/Constraint.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/DependentRequired/DependentRequired.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/PropertyNames.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/UnevaluatedItems.jsx
  src/core/plugins/json-schema-2020-12/components/keywords/UnevaluatedProperties.jsx
  test/e2e-cypress/e2e/features/plugins/json-schema-2020-12/empty-schema.cy.js
  test/e2e-cypress/static/documents/features/json-schema-2020-12-empty-schema.yaml
Labels: type: bug, version: 5.x

#10344 Fix error msg for out-of-range value of int param
  src/core/utils/index.js
  test/unit/core/utils.js
Labels: type: enhancement, version: 5.x

#10259 fix(style): do not shrink operationId if there is sufficient space
  src/style/_layout.scss
Labels: P3, cat: rendering, pull-request-welcome

#10410 fix(docker): address multiple HIGH security vulnerabilities
  Dockerfile
Labels: cat: security, cat: docker, security vulnerability, security fix, docker

#10411 fix(json-schema-2020-12): infer type string when contentEncoding or contentMediaType is present
  src/core/plugins/json-schema-2020-12/fn.js
Labels: type: bug, version: 5.x, specification: 3.1

#10409 fix: align OpenAPI 3.x.y file uploads with specification
  src/core/config/defaults.js
  src/core/config/type-cast/mappings.js
  src/core/plugins/json-schema-2020-12/fn.js
  src/core/plugins/json-schema-2020-12/index.js
  src/core/plugins/json-schema-5/components/json-schema-components.jsx
  src/core/plugins/json-schema-5/fn.js
  src/core/plugins/json-schema-5/index.js
  src/core/plugins/oas3/components/request-body.jsx
  src/core/plugins/oas3/fn.js
  src/core/plugins/oas3/index.js
  src/core/plugins/oas3/wrap-components/json-schema-string.jsx
  src/core/plugins/oas31/after-load.js
  src/core/plugins/oas31/oas3-extensions/fn.js
  test/e2e-cypress/e2e/features/plugins/oas3/request-body-upload-file.cy.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-request-body-upload-file.cy.js
  test/e2e-cypress/e2e/features/request-body-upload-file.cy.js
  test/e2e-cypress/static/documents/features/oas3-request-body-upload-file.yaml
  test/e2e-cypress/static/documents/features/oas31-request-body-upload-file.yaml
  test/unit/core/plugins/json-schema-5/components/json-schema-form.jsx
Labels: type: bug, specification: 3.x, version: 5.x, specification: 3.1

#10412 feat(oas31): display file upload input when contentMediaType or contentEncoding is present
  src/core/plugins/oas31/oas3-extensions/fn.js
  test/e2e-cypress/e2e/features/plugins/oas31/oas31-request-body-upload-file.cy.js
  test/e2e-cypress/static/documents/features/oas31-request-body-upload-file.yaml
Labels: type: enhancement, version: 5.x, specification: 3.1
